<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WorkerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $surnames =[
            "ARNAUD ",
            "AUBIN ",
            "AZZOUZ ",
            "BARBIER ",
            "BARDEAUX ",
            "BAUDIN ",
            "BELHATRI ",
            "BENGHALEM  ",
            "BEULE ",
            "BINAY ",
            "BIZON ",
            "BODIN ",
            "BONSERGENT ",
            "BOUGOULA ",
            "BOURGEOIS ",
            "BOURMAUD ",
            "BOUTTIER ",
            "BRIAND",
            "CADEAU ",
            "CAMILLE ",
            "CASSIALA MPESE ",
            "CHARBONNIER ",
            "CHARTIER  ",
            "CHASSEREAU ",
            "CHAUVIN ",
            "CHEVALIER ",
            "COLLEATTE ",
            "CRETON ",
            "CUMUNEL ",
            "DELOUCHE ",
            "DOMINGOS MENDES ",
            "DUPUY ",
            "DURAND ",
            "FARRA-FROND ",
            "FASSEL ",
            "FAVERJON ",
            "FOUASSIER ",
            "FOUQUERON ",
            "GIBOULET ",
            "GIBOULET ",
            "GIRARD ",
            "GOXE ",
            "GUIBE ",
            "GUILLOCHEAU ",
            "HAMON ",
            "HAYE ",
            "KOUDA ",
            "LE THIEC ",
            "LEBAUDY ",
            "LECLERC ",
            "LEGER ",
            "LEMASSON ",
            "LEROYER ",
            "LIEFFRIG ",
            "MADIOT ",
            "MAHE ",
            "MATHIEU ",
            "MAURICE ",
            "MENON ",
            "MEUNIER ",
            "MEUX ",
            "MONCHO ",
            "MONCOIFFET ",
            "MOUTAULT ",
            "MUSARD ",
            "MUTOMBO CARTIER ",
            "NGOMA ",
            "NIMSGERN ",
            "NOURI ",
            "OLIVARES ",
            "OMONT ",
            "ONILLON ",
            "PASQUIER ",
            "PERRAIS ",
            "RABIN ",
            "REBOUX ",
            "RENAUD ",
            "RICHARD ",
            "ROCHER ",
            "ROLLAND ",
            "ROULLE ",
            "SANCHEZ ",
            "SORIN ",
            "SOULLARD ",
            "TABGHI ",
            "TAGNE ",
            "TERRIEN ",
            "TRESSY ",
            "TRUONG ",
            "VEAU ",
            "VIGNE ",
            "VOLTZ ",

        ];
        $names = [
            "MATHIEU",
            "STEPHANE",
            "ABDELMALEK",
            "YANN",
            "SEBASTIEN",
            "MICKAEL",
            "OMAR",
            "MOURAD",
            "FRANCK",
            "DORIAN",
            "ROMUALD",
            "FREDERIC",
            "YOHANN",
            "ATMENE",
            "CORENTIN",
            "PATRICK",
            "DAMIEN",
            "JEAN-CHARLES",
            "SIMON",
            "PORQUET",
            "JODY",
            "CEDRIC",
            "JEAN PAUL",
            "PASCAL",
            "JEROM",
            "JEAN-PIERRE",
            "GAEL",
            "ALEXANDRE",
            "THOMAS",
            "OLIVIER",
            "CAFU",
            "FLORENT",
            "CHRISTOPHE",
            "BRANDON",
            "DAMIEN",
            "COLIN",
            "FLORENTIN",
            "JEAN-GABRIEL",
            "FRANCOIS",
            "VALENTIN",
            "BENJAMIN",
            "SEBASTIEN",
            "ANTOINE",
            "JOEL",
            "ANTOINEO",
            "TIMO",
            "ISMAEL",
            "ADRIEN",
            "ALEXIS",
            "GUILLAUME",
            "BRUNO",
            "BRUCE",
            "DAMIEN",
            "CHRISTOPHE",
            "PAUL",
            "PIERRE-MARIE",
            "ELYSA",
            "DAVID",
            "FAUSTIN",
            "ALEXIS",
            "NICOLAS",
            "THIBAUD",
            "PHILIPPE",
            "CHRISTOPHE",
            "FLORIAN",
            "CARTIER OVIDE",
            "ROLAND",
            "LOIC",
            "VICTOR",
            "FLORIAN",
            "FREDERIK",
            "THEO",
            "FLORIAN",
            "VALENTIN",
            "THIBAULT",
            "GUY",
            "KEVIN",
            "STEPHANE",
            "FLORIANE",
            "ERWAN",
            "YANN",
            "HUGO",
            "ALEXIS",
            "DENIS",
            "ABDELAZIZ",
            "GILLES",
            "BRICE",
            "YANN",
            "GMY-LAN",
            "THIERRY",
            "CHARLOTTE",
            "MARIE",

        ];

        foreach ($surnames as $surname){
            \DB::table("workers")->insert(["surname" =>$surname]);
        }
        foreach ($names as $name){
            \DB::table("workers")->insert(["name" =>$name]);
        }
    }
}
